// LAUREN — catalogue.
// Photography is the store's own; image keys map to assets/products/<key>.jpg
// Products that share a `family` are the same style in another colourway and
// cross-link as swatches on the product page.

export const CATEGORIES = [
  { id: 'all',   name: 'همه محصولات', sub: 'کالکشن کامل' },
  { id: 'polo',  name: 'پولوشرت',     sub: 'Polo' },
  { id: 'knit',  name: 'بافت',        sub: 'Knitwear' },
  { id: 'set',   name: 'ست',          sub: 'Co-ord' },
];

const CARE = 'شست‌وشو با آب سرد، پشت‌ورو. سفیدکننده ممنوع. اتوی ملایم از پشت پارچه.';

export const PRODUCTS = [
  {
    id: 'polo-noir',
    family: 'pique-stripe',
    cat: 'polo',
    title: 'پولوشرت پیکه نواردوزی',
    latin: 'Piqué Tipped Polo',
    colorName: 'مشکی',
    swatch: '#111116',
    price: 3_450_000,
    compareAt: 4_200_000,
    badge: 'sale',
    fabric: 'پنبه پیکه ۹۵٪ · الاستان ۵٪',
    fit: 'رگولار — یک سایز بزرگ‌تر برای فرم آزادتر',
    origin: 'ترکیه',
    desc: 'پولوشرت پیکه با یقه ریب و نوارِ دولاین سفید روی یقه و سرِ آستین. پنل رنگی روی بازو و دکمه‌های نارنجی، امضای این مدل است. تنه‌ی وزن‌دار پیکه که بعد از چند بار شست‌وشو هم فرمش را نگه می‌دارد.',
    highlights: ['یقه ریب خودرنگ با نوار کنتراست', 'پنل رنگی روی آستین', 'دکمه‌ی نارنجی دست‌دوز', 'درزهای دوبل در سرشانه'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    lowStock: ['XXL'],
    gallery: ['polo-noir', 'polo-noir--detail'],
    care: CARE,
  },
  {
    id: 'polo-blanc',
    family: 'pique-stripe',
    cat: 'polo',
    title: 'پولوشرت پیکه نواردوزی',
    latin: 'Piqué Tipped Polo',
    colorName: 'سفید',
    swatch: '#f2f0eb',
    price: 3_450_000,
    badge: 'best',
    fabric: 'پنبه پیکه ۹۵٪ · الاستان ۵٪',
    fit: 'رگولار — یک سایز بزرگ‌تر برای فرم آزادتر',
    origin: 'ترکیه',
    desc: 'همان پولوشرت پیکه، این‌بار روی زمینه‌ی سفید که پنل سرمه‌ای و خط قرمز آستین را بیرون می‌کشد. انتخاب امنِ روزهای گرم، زیر کت یا تنها.',
    highlights: ['یقه ریب با نوار سرمه‌ای', 'پنل کنتراست روی آستین', 'دکمه‌ی نارنجی دست‌دوز', 'دوخت تمیزِ لبه‌ها'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    lowStock: ['S'],
    gallery: ['polo-blanc', 'polo-blanc--detail'],
    care: CARE,
  },
  {
    id: 'polo-steel',
    family: 'pique-stripe',
    cat: 'polo',
    title: 'پولوشرت پیکه نواردوزی',
    latin: 'Piqué Tipped Polo',
    colorName: 'آبی فولادی',
    swatch: '#7a90ab',
    price: 3_450_000,
    badge: 'new',
    fabric: 'پنبه پیکه ۹۵٪ · الاستان ۵٪',
    fit: 'رگولار — یک سایز بزرگ‌تر برای فرم آزادتر',
    origin: 'ترکیه',
    desc: 'رنگ‌بندی تازه‌ی این فصل؛ آبیِ فولادیِ سرد که با شلوار کرم و سفید بهترین ترکیب را می‌سازد.',
    highlights: ['رنگ‌بندی محدود این فصل', 'یقه ریب با نوار کنتراست', 'پنل رنگی روی آستین', 'دکمه‌ی نارنجی دست‌دوز'],
    sizes: ['M', 'L', 'XL'],
    lowStock: ['M'],
    gallery: ['polo-steel', 'polo-steel--detail'],
    care: CARE,
  },
  {
    id: 'polo-jade',
    family: 'jacquard-knit',
    cat: 'polo',
    title: 'پولوشرت بافت ژاکارد',
    latin: 'Jacquard Knit Polo',
    colorName: 'سبز جِید',
    swatch: '#3f7f66',
    price: 4_850_000,
    badge: 'new',
    fabric: 'ویسکوز ۷۰٪ · پنبه ۳۰٪',
    fit: 'نیمه‌اسلیم',
    origin: 'ترکیه',
    desc: 'بافت ژاکارد با طرح تمام‌سطح که فقط زیر نور دیده می‌شود — از دور یک‌رنگ است، از نزدیک پُر جزئیات. سطح براق و لطیف با افتِ سنگین.',
    highlights: ['بافت ژاکارد تمام‌سطح', 'سطح براق با افت سنگین', 'یقه‌ی خوش‌فرم بدون آهار', 'مناسب مهمانی و شب'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    lowStock: [],
    gallery: ['polo-jade', 'polo-jade--detail'],
    care: CARE,
  },
  {
    id: 'polo-bordeaux',
    family: 'jacquard-knit',
    cat: 'polo',
    title: 'پولوشرت بافت ژاکارد',
    latin: 'Jacquard Knit Polo',
    colorName: 'زرشکی',
    swatch: '#7b3546',
    price: 4_850_000,
    fabric: 'ویسکوز ۷۰٪ · پنبه ۳۰٪',
    fit: 'نیمه‌اسلیم',
    origin: 'ترکیه',
    desc: 'همان بافت ژاکارد در زرشکیِ عمیق. رنگی که زیر نور شب گرم می‌شود و با مشکی و کرم عالی می‌نشیند.',
    highlights: ['بافت ژاکارد تمام‌سطح', 'رنگ عمیق و گرم', 'یقه‌ی خوش‌فرم بدون آهار', 'مناسب مهمانی و شب'],
    sizes: ['M', 'L', 'XL'],
    lowStock: ['XL'],
    gallery: ['polo-bordeaux', 'polo-bordeaux--detail'],
    care: CARE,
  },
  {
    id: 'polo-collar',
    family: 'contrast-collar',
    cat: 'polo',
    title: 'پولوشرت یقه‌ترکیبی',
    latin: 'Contrast Collar Polo',
    colorName: 'مشکی / کرم',
    swatch: '#1a1a1e',
    price: 4_250_000,
    badge: 'best',
    fabric: 'مودال ۶۰٪ · پنبه ۴۰٪',
    fit: 'رگولار',
    origin: 'ترکیه',
    desc: 'یقه‌ی پهنِ کرم روی تنه‌ی مشکی — کنتراستی که همه‌ی کار را می‌کند. دکمه‌های صدفی و پارچه‌ی خنکِ مودال برای شب‌های گرم.',
    highlights: ['یقه‌ی پهن کنتراست', 'دکمه‌ی صدفی', 'پارچه‌ی خنک مودال', 'یقه‌ی فرم‌گرفته با لایی نرم'],
    sizes: ['S', 'M', 'L', 'XL'],
    lowStock: ['S'],
    gallery: ['polo-collar', 'polo-collar--detail'],
    care: CARE,
  },
  {
    id: 'knit-ivory',
    family: 'rib-knit',
    cat: 'knit',
    title: 'پولوشرت بافت ریب',
    latin: 'Ribbed Knit Polo',
    colorName: 'شیری',
    swatch: '#efece4',
    price: 5_200_000,
    badge: 'new',
    fabric: 'ویسکوز ۵۵٪ · پلی‌آمید ۴۵٪',
    fit: 'اسلیم',
    origin: 'ترکیه',
    desc: 'بافت ریبِ باریک با یقه و لبه‌های آجریِ کنتراست. یقه‌ی باز بدون دکمه، برشِ کوتاه — با شلوار پارچه‌ای بهترین حالتش را دارد.',
    highlights: ['بافت ریب باریک', 'یقه و مچ آجری کنتراست', 'یقه‌ی باز بدون دکمه', 'برش کوتاه و خوش‌افت'],
    sizes: ['S', 'M', 'L', 'XL'],
    lowStock: ['XL'],
    gallery: ['knit-ivory', 'knit-ivory--detail'],
    care: CARE,
  },
  {
    id: 'knit-sand',
    family: 'rib-knit',
    cat: 'knit',
    title: 'پولوشرت بافت ریب',
    latin: 'Ribbed Knit Polo',
    colorName: 'شنی',
    swatch: '#c4a87e',
    price: 5_200_000,
    fabric: 'ویسکوز ۵۵٪ · پلی‌آمید ۴۵٪',
    fit: 'اسلیم',
    origin: 'ترکیه',
    desc: 'نسخه‌ی شنیِ همان بافت ریب؛ گرم‌تر، آرام‌تر و راحت‌تر برای ست‌کردن با قهوه‌ای و زیتونی.',
    highlights: ['بافت ریب باریک', 'یقه و مچ آجری کنتراست', 'رنگ خنثی و ست‌شدنی', 'برش کوتاه و خوش‌افت'],
    sizes: ['M', 'L', 'XL'],
    lowStock: [],
    gallery: ['knit-sand', 'knit-sand--detail'],
    care: CARE,
  },
  {
    id: 'set-onyx',
    family: 'jacquard-suit',
    cat: 'set',
    title: 'ست پولوشرت و شلوار ژاکارد',
    latin: 'Jacquard Polo & Trouser Set',
    colorName: 'مشکی / شیری',
    swatch: '#141418',
    price: 8_900_000,
    compareAt: 10_400_000,
    badge: 'sale',
    fabric: 'پولوشرت: بافت ژاکارد · شلوار: کرپ کش‌دار',
    fit: 'پولوشرت رگولار · شلوار فاق متوسط',
    origin: 'ترکیه',
    desc: 'ستِ کامل: پولوشرت بافت با طرح هندسیِ برجسته و شلوار پارچه‌ایِ شیری با فرمِ راست. یک انتخاب و کل استایل بسته است.',
    highlights: ['ست کامل بالا و پایین', 'طرح هندسی برجسته روی بافت', 'شلوار کرپ با کش کمر پنهان', 'قابل پوشیدن به‌صورت جدا'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    lowStock: ['XXL'],
    gallery: ['set-onyx', 'set-onyx--detail'],
    care: CARE,
  },
  {
    id: 'set-cacao',
    family: 'ringer-set',
    cat: 'set',
    title: 'ست تی‌شرت و شلوارک',
    latin: 'Ringer Tee & Short Set',
    colorName: 'کاکائویی',
    swatch: '#6b4630',
    price: 5_600_000,
    badge: 'best',
    fabric: 'اسکابا ۹۲٪ · اسپاندکس ۸٪',
    fit: 'اورسایز ملایم',
    origin: 'ترکیه',
    desc: 'ست راحتیِ کاکائویی با نوارِ کرمِ دورِ یقه، سرِ آستین و لبه‌ی شلوارک. پارچه‌ی اسکابا که نه چروک می‌شود نه وا می‌رود.',
    highlights: ['نوار کنتراست کرم', 'پارچه‌ی ضدچروک اسکابا', 'شلوارک با بند کشی', 'دو جیب کناری'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    lowStock: [],
    gallery: ['set-cacao', 'set-cacao--detail'],
    care: CARE,
  },
  {
    id: 'set-olive',
    family: 'ringer-set',
    cat: 'set',
    title: 'ست تی‌شرت و شلوارک',
    latin: 'Ringer Tee & Short Set',
    colorName: 'زیتونی',
    swatch: '#5f6234',
    price: 5_600_000,
    badge: 'new',
    fabric: 'اسکابا ۹۲٪ · اسپاندکس ۸٪',
    fit: 'اورسایز ملایم',
    origin: 'ترکیه',
    desc: 'زیتونیِ ارتشی با نوارِ کرم — همان ستِ راحتی با رنگی که کمتر پیدا می‌شود.',
    highlights: ['نوار کنتراست کرم', 'پارچه‌ی ضدچروک اسکابا', 'شلوارک با بند کشی', 'دو جیب کناری'],
    sizes: ['L', 'XL', 'XXL'],
    lowStock: ['L'],
    gallery: ['set-olive', 'set-olive--detail'],
    care: CARE,
  },
  {
    id: 'set-slate',
    family: 'ringer-set',
    cat: 'set',
    title: 'ست تی‌شرت و شلوارک',
    latin: 'Ringer Tee & Short Set',
    colorName: 'خاکستری دودی',
    swatch: '#6d6a63',
    price: 5_600_000,
    fabric: 'اسکابا ۹۲٪ · اسپاندکس ۸٪',
    fit: 'اورسایز ملایم',
    origin: 'ترکیه',
    desc: 'خاکستریِ دودیِ خنثی؛ ستی که با هر کفشی جواب می‌دهد.',
    highlights: ['نوار کنتراست کرم', 'پارچه‌ی ضدچروک اسکابا', 'شلوارک با بند کشی', 'دو جیب کناری'],
    sizes: ['M', 'L', 'XL'],
    lowStock: [],
    gallery: ['set-slate', 'set-slate--detail'],
    care: CARE,
  },
];

export const SIZE_GUIDE = {
  cols: ['سایز', 'دور سینه (cm)', 'قد بالاتنه (cm)', 'سرشانه (cm)', 'قد پیشنهادی'],
  rows: [
    ['S',   '96 – 100', '68', '43', '165 – 172'],
    ['M',   '100 – 106', '70', '45', '170 – 178'],
    ['L',   '106 – 112', '72', '47', '176 – 184'],
    ['XL',  '112 – 118', '74', '49', '182 – 190'],
    ['XXL', '118 – 126', '76', '51', '186 – 196'],
  ],
  note: 'اندازه‌ها روی لباسِ خوابیده گرفته شده و تا ۲ سانتی‌متر خطا طبیعی است. اگر بین دو سایز هستید، سایز بزرگ‌تر را بگیرید.',
};

export const EDITORIAL = [
  {
    id: 'atlas',
    kicker: 'کالکشن تابستان',
    title: 'بافت‌هایی که\nنور را می‌گیرند',
    body: 'ژاکاردهای این فصل از دور ساده‌اند و از نزدیک پر جزئیات. طرح روی پارچه بافته شده، نه چاپ‌شده — برای همین با شست‌وشو نمی‌رود.',
    image: 'polo-jade--detail',
    cta: { label: 'دیدن بافت‌ها', href: '#/shop?cat=knit' },
  },
  {
    id: 'sets',
    kicker: 'ست‌های کامل',
    title: 'یک انتخاب،\nکل استایل',
    body: 'ست‌های بالا و پایین که از قبل با هم هماهنگ شده‌اند. صبح‌ها دیگر لازم نیست فکر کنید چه چیزی به چه چیزی می‌آید.',
    image: 'set-cacao--detail',
    cta: { label: 'دیدن ست‌ها', href: '#/shop?cat=set' },
  },
];

export const FAQ = [
  {
    q: 'چطور سایزم را انتخاب کنم؟',
    a: 'جدول سایز را در صفحه‌ی هر محصول ببینید؛ اندازه‌ها روی لباسِ خوابیده گرفته شده. اگر بین دو سایز هستید سایز بزرگ‌تر را بگیرید. برای مشورت مستقیم، در واتساپ قد و وزنتان را بفرستید.',
  },
  {
    q: 'ارسال چقدر طول می‌کشد؟',
    a: 'داخل تبریز با پیک اختصاصی همان روز. شهرستان با پست پیشتاز ۲ تا ۴ روز کاری و با تیپاکس ۱ تا ۳ روز کاری. سفارش‌های بالای ۵٬۰۰۰٬۰۰۰ تومان ارسال رایگان دارند.',
  },
  {
    q: 'اگر سایز نشد می‌توانم تعویض کنم؟',
    a: 'بله. تا ۷ روز پس از تحویل، با شرط استفاده‌نشدن و سالم‌بودن اتیکت، تعویض سایز رایگان است. هزینه‌ی ارسالِ برگشت با ماست.',
  },
  {
    q: 'امتیازها چطور کار می‌کنند؟',
    a: 'به ازای هر ۱۰٬۰۰۰ تومان خرید، ۱ امتیاز می‌گیرید و هر امتیاز ۵۰۰ تومان اعتبار برای خریدهای بعدی است. با بالا رفتن امتیاز، سطح باشگاه و مزایای شما هم ارتقا پیدا می‌کند.',
  },
  {
    q: 'اجناس اورجینال هستند؟',
    a: 'همه‌ی محصولات مستقیم از تولیدکننده‌های ترکیه تأمین می‌شوند و پیش از ورود به فروشگاه از نظر دوخت و پارچه کنترل می‌شوند.',
  },
  {
    q: 'حضوری هم می‌توانم خرید کنم؟',
    a: 'حتماً — تبریز، خیابان ولیعصر، مرکز خرید اطلس، طبقه GC. سفارش آنلاین را هم می‌توانید حضوری تحویل بگیرید و پرو کنید.',
  },
];

export const byId = (id) => PRODUCTS.find((p) => p.id === id);
export const family = (p) => PRODUCTS.filter((x) => x.family === p.family);
