// LAUREN — catalogue.
// Photography is the store's own; image keys map to assets/products/<key>.jpg
// Products that share a `family` are the same style in another colourway and
// cross-link as swatches on the product page.

export const CATEGORIES = [
  { id: 'all',   name: 'همه محصولات', sub: 'کالکشن کامل' },
  { id: 'polo',  name: 'پولوشرت',     sub: 'Polo' },
  { id: 'knit',  name: 'بافت',        sub: 'Knitwear' },
  { id: 'set',   name: 'ست',          sub: 'Co-ord' },
];

const CARE = 'شست‌وشو با آب سرد، پشت‌ورو. سفیدکننده ممنوع. اتوی ملایم از پشت پارچه.';

export const PRODUCTS = [
  {
    id: 'polo-noir',
    ref: '01',
    family: 'pique-stripe',
    cat: 'polo',
    title: 'پولوشرت پیکه نواردوزی',
    latin: 'Piqué Tipped Polo',
    colorName: 'مشکی',
    swatch: '#111116',
    price: 3_450_000,
    compareAt: 4_200_000,
    badge: 'sale',
    fabric: 'پنبه پیکه ۹۵٪ · الاستان ۵٪',
    fit: 'رگولار — یک سایز بزرگ‌تر برای فرم آزادتر',
    origin: 'ترکیه',
    desc: 'پولوشرت پیکه با یقه ریب و نوارِ دولاین سفید روی یقه و سرِ آستین. پنل رنگی روی بازو و دکمه‌های نارنجی، امضای این مدل است. تنه‌ی وزن‌دار پیکه که بعد از چند بار شست‌وشو هم فرمش را نگه می‌دارد.',
    highlights: ['یقه ریب خودرنگ با نوار کنتراست', 'پنل رنگی روی آستین', 'دکمه‌ی نارنجی دست‌دوز', 'درزهای دوبل در سرشانه'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 6, M: 6, L: 6, XL: 6, XXL: 2 },
    sizeChart: 'top',
    gallery: ['polo-noir', 'polo-noir--detail'],
    care: CARE,
  },
  {
    id: 'polo-blanc',
    ref: '02',
    family: 'pique-stripe',
    cat: 'polo',
    title: 'پولوشرت پیکه نواردوزی',
    latin: 'Piqué Tipped Polo',
    colorName: 'سفید',
    swatch: '#f2f0eb',
    price: 3_450_000,
    badge: 'best',
    fabric: 'پنبه پیکه ۹۵٪ · الاستان ۵٪',
    fit: 'رگولار — یک سایز بزرگ‌تر برای فرم آزادتر',
    origin: 'ترکیه',
    desc: 'همان پولوشرت پیکه، این‌بار روی زمینه‌ی سفید که پنل سرمه‌ای و خط قرمز آستین را بیرون می‌کشد. انتخاب امنِ روزهای گرم، زیر کت یا تنها.',
    highlights: ['یقه ریب با نوار سرمه‌ای', 'پنل کنتراست روی آستین', 'دکمه‌ی نارنجی دست‌دوز', 'دوخت تمیزِ لبه‌ها'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 2, M: 6, L: 6, XL: 6, XXL: 6 },
    sizeChart: 'top',
    gallery: ['polo-blanc', 'polo-blanc--detail'],
    care: CARE,
  },
  {
    id: 'polo-steel',
    ref: '03',
    family: 'pique-stripe',
    cat: 'polo',
    title: 'پولوشرت پیکه نواردوزی',
    latin: 'Piqué Tipped Polo',
    colorName: 'آبی فولادی',
    swatch: '#7a90ab',
    price: 3_450_000,
    badge: 'new',
    fabric: 'پنبه پیکه ۹۵٪ · الاستان ۵٪',
    fit: 'رگولار — یک سایز بزرگ‌تر برای فرم آزادتر',
    origin: 'ترکیه',
    desc: 'رنگ‌بندی تازه‌ی این فصل؛ آبیِ فولادیِ سرد که با شلوار کرم و سفید بهترین ترکیب را می‌سازد.',
    highlights: ['رنگ‌بندی محدود این فصل', 'یقه ریب با نوار کنتراست', 'پنل رنگی روی آستین', 'دکمه‌ی نارنجی دست‌دوز'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 0, M: 2, L: 6, XL: 6, XXL: 0 },
    sizeChart: 'top',
    gallery: ['polo-steel', 'polo-steel--detail'],
    care: CARE,
  },
  {
    id: 'polo-jade',
    ref: '04',
    family: 'jacquard-knit',
    cat: 'polo',
    title: 'پولوشرت بافت ژاکارد',
    latin: 'Jacquard Knit Polo',
    colorName: 'سبز جِید',
    swatch: '#3f7f66',
    price: 4_850_000,
    badge: 'new',
    fabric: 'ویسکوز ۷۰٪ · پنبه ۳۰٪',
    fit: 'نیمه‌اسلیم',
    origin: 'ترکیه',
    desc: 'بافت ژاکارد با طرح تمام‌سطح که فقط زیر نور دیده می‌شود — از دور یک‌رنگ است، از نزدیک پُر جزئیات. سطح براق و لطیف با افتِ سنگین.',
    highlights: ['بافت ژاکارد تمام‌سطح', 'سطح براق با افت سنگین', 'یقه‌ی خوش‌فرم بدون آهار', 'مناسب مهمانی و شب'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 0, M: 6, L: 6, XL: 6, XXL: 6 },
    sizeChart: 'top',
    gallery: ['polo-jade', 'polo-jade--detail'],
    care: CARE,
  },
  {
    id: 'polo-bordeaux',
    ref: '05',
    family: 'jacquard-knit',
    cat: 'polo',
    title: 'پولوشرت بافت ژاکارد',
    latin: 'Jacquard Knit Polo',
    colorName: 'زرشکی',
    swatch: '#7b3546',
    price: 4_850_000,
    fabric: 'ویسکوز ۷۰٪ · پنبه ۳۰٪',
    fit: 'نیمه‌اسلیم',
    origin: 'ترکیه',
    desc: 'همان بافت ژاکارد در زرشکیِ عمیق. رنگی که زیر نور شب گرم می‌شود و با مشکی و کرم عالی می‌نشیند.',
    highlights: ['بافت ژاکارد تمام‌سطح', 'رنگ عمیق و گرم', 'یقه‌ی خوش‌فرم بدون آهار', 'مناسب مهمانی و شب'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 0, M: 6, L: 6, XL: 2, XXL: 0 },
    sizeChart: 'top',
    gallery: ['polo-bordeaux', 'polo-bordeaux--detail'],
    care: CARE,
  },
  {
    id: 'polo-collar',
    ref: '06',
    family: 'contrast-collar',
    cat: 'polo',
    title: 'پولوشرت یقه‌ترکیبی',
    latin: 'Contrast Collar Polo',
    colorName: 'مشکی / کرم',
    swatch: '#1a1a1e',
    price: 4_250_000,
    badge: 'best',
    fabric: 'مودال ۶۰٪ · پنبه ۴۰٪',
    fit: 'رگولار',
    origin: 'ترکیه',
    desc: 'یقه‌ی پهنِ کرم روی تنه‌ی مشکی — کنتراستی که همه‌ی کار را می‌کند. دکمه‌های صدفی و پارچه‌ی خنکِ مودال برای شب‌های گرم.',
    highlights: ['یقه‌ی پهن کنتراست', 'دکمه‌ی صدفی', 'پارچه‌ی خنک مودال', 'یقه‌ی فرم‌گرفته با لایی نرم'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 2, M: 6, L: 6, XL: 6, XXL: 0 },
    sizeChart: 'top',
    gallery: ['polo-collar', 'polo-collar--detail'],
    care: CARE,
  },
  {
    id: 'knit-ivory',
    ref: '07',
    family: 'rib-knit',
    cat: 'knit',
    title: 'پولوشرت بافت ریب',
    latin: 'Ribbed Knit Polo',
    colorName: 'شیری',
    swatch: '#efece4',
    price: 5_200_000,
    badge: 'new',
    fabric: 'ویسکوز ۵۵٪ · پلی‌آمید ۴۵٪',
    fit: 'اسلیم',
    origin: 'ترکیه',
    desc: 'بافت ریبِ باریک با یقه و لبه‌های آجریِ کنتراست. یقه‌ی باز بدون دکمه، برشِ کوتاه — با شلوار پارچه‌ای بهترین حالتش را دارد.',
    highlights: ['بافت ریب باریک', 'یقه و مچ آجری کنتراست', 'یقه‌ی باز بدون دکمه', 'برش کوتاه و خوش‌افت'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 6, M: 6, L: 6, XL: 2, XXL: 0 },
    sizeChart: 'top',
    gallery: ['knit-ivory', 'knit-ivory--detail'],
    care: CARE,
  },
  {
    id: 'knit-sand',
    ref: '08',
    family: 'rib-knit',
    cat: 'knit',
    title: 'پولوشرت بافت ریب',
    latin: 'Ribbed Knit Polo',
    colorName: 'شنی',
    swatch: '#c4a87e',
    price: 5_200_000,
    fabric: 'ویسکوز ۵۵٪ · پلی‌آمید ۴۵٪',
    fit: 'اسلیم',
    origin: 'ترکیه',
    desc: 'نسخه‌ی شنیِ همان بافت ریب؛ گرم‌تر، آرام‌تر و راحت‌تر برای ست‌کردن با قهوه‌ای و زیتونی.',
    highlights: ['بافت ریب باریک', 'یقه و مچ آجری کنتراست', 'رنگ خنثی و ست‌شدنی', 'برش کوتاه و خوش‌افت'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 0, M: 6, L: 6, XL: 6, XXL: 0 },
    sizeChart: 'top',
    gallery: ['knit-sand', 'knit-sand--detail'],
    care: CARE,
  },
  {
    id: 'set-onyx',
    ref: '09',
    family: 'jacquard-suit',
    cat: 'set',
    title: 'ست پولوشرت و شلوار ژاکارد',
    latin: 'Jacquard Polo & Trouser Set',
    colorName: 'مشکی / شیری',
    swatch: '#141418',
    price: 8_900_000,
    compareAt: 10_400_000,
    badge: 'sale',
    fabric: 'پولوشرت: بافت ژاکارد · شلوار: کرپ کش‌دار',
    fit: 'پولوشرت رگولار · شلوار فاق متوسط',
    origin: 'ترکیه',
    desc: 'ستِ کامل: پولوشرت بافت با طرح هندسیِ برجسته و شلوار پارچه‌ایِ شیری با فرمِ راست. یک انتخاب و کل استایل بسته است.',
    highlights: ['ست کامل بالا و پایین', 'طرح هندسی برجسته روی بافت', 'شلوار کرپ با کش کمر پنهان', 'قابل پوشیدن به‌صورت جدا'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 0, M: 6, L: 6, XL: 6, XXL: 2 },
    sizeChart: 'set',
    gallery: ['set-onyx', 'set-onyx--detail'],
    care: CARE,
  },
  {
    id: 'set-cacao',
    ref: '10',
    family: 'ringer-set',
    cat: 'set',
    title: 'ست تی‌شرت و شلوارک',
    latin: 'Ringer Tee & Short Set',
    colorName: 'کاکائویی',
    swatch: '#6b4630',
    price: 5_600_000,
    badge: 'best',
    fabric: 'اسکابا ۹۲٪ · اسپاندکس ۸٪',
    fit: 'اورسایز ملایم',
    origin: 'ترکیه',
    desc: 'ست راحتیِ کاکائویی با نوارِ کرمِ دورِ یقه، سرِ آستین و لبه‌ی شلوارک. پارچه‌ی اسکابا که نه چروک می‌شود نه وا می‌رود.',
    highlights: ['نوار کنتراست کرم', 'پارچه‌ی ضدچروک اسکابا', 'شلوارک با بند کشی', 'دو جیب کناری'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 0, M: 6, L: 6, XL: 6, XXL: 6 },
    sizeChart: 'set',
    gallery: ['set-cacao', 'set-cacao--detail'],
    care: CARE,
  },
  {
    id: 'set-olive',
    ref: '11',
    family: 'ringer-set',
    cat: 'set',
    title: 'ست تی‌شرت و شلوارک',
    latin: 'Ringer Tee & Short Set',
    colorName: 'زیتونی',
    swatch: '#5f6234',
    price: 5_600_000,
    badge: 'new',
    fabric: 'اسکابا ۹۲٪ · اسپاندکس ۸٪',
    fit: 'اورسایز ملایم',
    origin: 'ترکیه',
    desc: 'زیتونیِ ارتشی با نوارِ کرم — همان ستِ راحتی با رنگی که کمتر پیدا می‌شود.',
    highlights: ['نوار کنتراست کرم', 'پارچه‌ی ضدچروک اسکابا', 'شلوارک با بند کشی', 'دو جیب کناری'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 0, M: 0, L: 2, XL: 6, XXL: 6 },
    sizeChart: 'set',
    gallery: ['set-olive', 'set-olive--detail'],
    care: CARE,
  },
  {
    id: 'set-slate',
    ref: '12',
    family: 'ringer-set',
    cat: 'set',
    title: 'ست تی‌شرت و شلوارک',
    latin: 'Ringer Tee & Short Set',
    colorName: 'خاکستری دودی',
    swatch: '#6d6a63',
    price: 5_600_000,
    fabric: 'اسکابا ۹۲٪ · اسپاندکس ۸٪',
    fit: 'اورسایز ملایم',
    origin: 'ترکیه',
    desc: 'خاکستریِ دودیِ خنثی؛ ستی که با هر کفشی جواب می‌دهد.',
    highlights: ['نوار کنتراست کرم', 'پارچه‌ی ضدچروک اسکابا', 'شلوارک با بند کشی', 'دو جیب کناری'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 0, M: 6, L: 6, XL: 6, XXL: 0 },
    sizeChart: 'set',
    gallery: ['set-slate', 'set-slate--detail'],
    care: CARE,
  },
];

export const SIZE_CHARTS = {
  top: {
    name: 'بالاتنه — برش معمولی',
    cols: ['سایز', 'دور سینه (cm)', 'قد بالاتنه (cm)', 'سرشانه (cm)', 'قد پیشنهادی'],
    rows: [
      ['S',   '96 – 100',  '68', '43', '165 – 172'],
      ['M',   '100 – 106', '70', '45', '170 – 178'],
      ['L',   '106 – 112', '72', '47', '176 – 184'],
      ['XL',  '112 – 118', '74', '49', '182 – 190'],
      ['XXL', '118 – 126', '76', '51', '186 – 196'],
    ],
  },
  relaxed: {
    name: 'بالاتنه — برش اورسایز',
    cols: ['سایز', 'دور سینه (cm)', 'قد بالاتنه (cm)', 'سرشانه (cm)', 'قد پیشنهادی'],
    rows: [
      ['S',   '104 – 108', '70', '47', '165 – 172'],
      ['M',   '108 – 114', '72', '49', '170 – 178'],
      ['L',   '114 – 120', '74', '51', '176 – 184'],
      ['XL',  '120 – 126', '76', '53', '182 – 190'],
      ['XXL', '126 – 132', '78', '55', '186 – 196'],
    ],
  },
  set: {
    name: 'شلوار و شلوارک',
    cols: ['سایز', 'دور کمر (cm)', 'دور باسن (cm)', 'قد پا (cm)', 'قد فاق (cm)'],
    rows: [
      ['S',   '74 – 80',   '92 – 96',   '98',  '26'],
      ['M',   '80 – 86',   '96 – 100',  '100', '27'],
      ['L',   '86 – 92',   '100 – 106', '102', '28'],
      ['XL',  '92 – 98',   '106 – 112', '104', '29'],
      ['XXL', '98 – 106',  '112 – 118', '106', '30'],
    ],
  },
};

export const SIZE_NOTE =
  'اندازه‌ها روی لباسِ خوابیده گرفته شده و تا ۲ سانتی‌متر خطا طبیعی است. ' +
  'اگر بین دو سایز هستید، سایز بزرگ‌تر را بگیرید.';

/** The charts a product needs: a set needs its trouser table too. */
export const chartsFor = (p) => (p.sizeChart === 'set'
  ? [SIZE_CHARTS.relaxed, SIZE_CHARTS.set]
  : [SIZE_CHARTS[p.sizeChart] || SIZE_CHARTS.top]);

export const EDITORIAL = [
  {
    id: 'atlas',
    kicker: 'کالکشن تابستان',
    title: 'بافت‌هایی که\nنور را می‌گیرند',
    body: 'ژاکاردهای این فصل از دور ساده‌اند و از نزدیک پر جزئیات. طرح روی پارچه بافته شده، نه چاپ‌شده — برای همین با شست‌وشو نمی‌رود.',
    image: 'polo-jade--detail',
    cta: { label: 'دیدن بافت‌ها', href: '#/shop?cat=knit' },
  },
  {
    id: 'sets',
    kicker: 'ست‌های کامل',
    title: 'یک انتخاب،\nکل استایل',
    body: 'ست‌های بالا و پایین که از قبل با هم هماهنگ شده‌اند. صبح‌ها دیگر لازم نیست فکر کنید چه چیزی به چه چیزی می‌آید.',
    image: 'set-cacao--detail',
    cta: { label: 'دیدن ست‌ها', href: '#/shop?cat=set' },
  },
];

export const FAQ = [
  {
    q: 'چطور سایزم را انتخاب کنم؟',
    a: 'جدول سایز را در صفحه‌ی هر محصول ببینید؛ اندازه‌ها روی لباسِ خوابیده گرفته شده. اگر بین دو سایز هستید سایز بزرگ‌تر را بگیرید. برای مشورت مستقیم، در واتساپ قد و وزنتان را بفرستید.',
  },
  {
    q: 'ارسال چقدر طول می‌کشد؟',
    a: 'داخل تبریز با پیک اختصاصی همان روز. شهرستان با پست پیشتاز ۲ تا ۴ روز کاری و با تیپاکس ۱ تا ۳ روز کاری. سفارش‌های بالای ۵٬۰۰۰٬۰۰۰ تومان ارسال رایگان دارند.',
  },
  {
    q: 'اگر سایز نشد می‌توانم تعویض کنم؟',
    a: 'بله. تا ۷ روز پس از تحویل، با شرط استفاده‌نشدن و سالم‌بودن اتیکت، تعویض سایز رایگان است. هزینه‌ی ارسالِ برگشت با ماست.',
  },
  {
    q: 'کیف اعتبار لارن چطور کار می‌کند؟',
    a: 'بعد از هر خرید، ۵٪ مبلغ کالاها به‌صورت اعتبار به کیف شما برمی‌گردد و در سفارش بعدی مستقیم از فاکتور کم می‌شود — بدون واحد و محاسبه‌ی اضافه. در هر سفارش تا نصف مبلغ کالاها را می‌توانید با اعتبار بپردازید. هرچه بیشتر خرید کنید سطحتان بالاتر می‌رود و درصد برگشت به ۷ و بعد ۱۰ درصد می‌رسد.',
  },
  {
    q: 'اجناس اورجینال هستند؟',
    a: 'همه‌ی محصولات مستقیم از تولیدکننده‌های ترکیه تأمین می‌شوند و پیش از ورود به فروشگاه از نظر دوخت و پارچه کنترل می‌شوند.',
  },
  {
    q: 'حضوری هم می‌توانم خرید کنم؟',
    a: 'حتماً — تبریز، خیابان ولیعصر، مرکز خرید اطلس، طبقه GC. سفارش آنلاین را هم می‌توانید حضوری تحویل بگیرید و پرو کنید.',
  },
];


/* --------------------------------------------------------- sample reviews --
 * FICTIONAL, and labelled as such everywhere they appear. They exist so the
 * client can see a populated review block in the preview; they are NOT from
 * Lauren's customers.
 *
 * Three rules hold the honesty, and all three are enforced in code, not here:
 *   1. every row renders a «نمونه» tag and never the «خرید تاییدشده» pill,
 *   2. they are excluded from reviewSummary(), so no average, count or bar
 *      a shopper reads as fact is ever moved by an invented opinion,
 *   3. shownReviews() drops them entirely when PREVIEW.enabled is false, so
 *      they cannot survive into a real shop by accident.
 * They are never written to state.reviews and so never reach localStorage.
 *
 * Timestamps are relative to load rather than fixed dates, so the preview does
 * not visibly rot between demos.
 */
const AGO = (days) => Date.now() - days * 86400000;

export const SAMPLE_REVIEWS = [
  { family: 'pique-stripe', name: 'امیر', stars: 5, ts: AGO(9), sample: true,
    body: 'پارچه‌ی پیکه‌اش وزن‌دار است و بعد از سه بار شست‌وشو هنوز فرمش را دارد. یقه‌اش شل نشد.' },
  { family: 'pique-stripe', name: 'سعید', stars: 4, ts: AGO(21), sample: true,
    body: 'سایز L برای قد ۱۸۰ و وزن ۷۸ اندازه بود. اگر فرم آزادتر می‌خواهید یک سایز بالاتر بگیرید.' },
  { family: 'jacquard-knit', name: 'محمد', stars: 5, ts: AGO(6), sample: true,
    body: 'بافتِ ژاکاردش از نزدیک خیلی بهتر از عکس است. زیر کت هم خوب می‌نشیند.' },
  { family: 'contrast-collar', name: 'رضا', stars: 4, ts: AGO(15), sample: true,
    body: 'دوختش تمیز است. یقه‌ی کنتراست دقیقاً همان رنگی است که در تصویر دیده می‌شود.' },
  { family: 'rib-knit', name: 'کامران', stars: 5, ts: AGO(11), sample: true,
    body: 'سبک است ولی گرم. برای پاییز تبریز دقیقاً همان چیزی بود که می‌خواستم.' },
  { family: 'rib-knit', name: 'بهزاد', stars: 4, ts: AGO(28), sample: true,
    body: 'رنگ شیری‌اش خیلی تمیز است؛ فقط مثل هر بافت روشنی، حواستان به لکه باشد.' },
  { family: 'jacquard-suit', name: 'آرش', stars: 5, ts: AGO(4), sample: true,
    body: 'ست را برای مراسم گرفتم. قد شلوار را کوتاه کردم و بقیه‌اش اندازه بود.' },
  { family: 'ringer-set', name: 'یاسر', stars: 4, ts: AGO(17), sample: true,
    body: 'راحت است و ست‌بودنش توی خیابان هم جواب می‌دهد. کش دور کمرش محکم است.' },
];

export const byId = (id) => PRODUCTS.find((p) => p.id === id);
export const family = (p) => PRODUCTS.filter((x) => x.family === p.family);
